### ISSUE TITLE
TypeError: Cannot convert AsyncDisk to diskimpl.PartitionAsyncDisk

### ISSUE THREAD

**Issue by cdetrio** [locore/yggdrasil#1]
I'm getting a cython TypeError when running the verifier.

```
$ python2 verify.py
Verifying WAL Layer.........................................0.228846 seconds

Failure.
E
======================================================================
ERROR: test_atomic (__main__.WALDiskTestRefinement)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_waldisk.py", line 99, in test_atomic
    self.__test_atomic(i + 1)
  File "test_waldisk.py", line 103, in __test_atomic
    d = self.create_impl(mach)
  File "test_waldisk.py", line 27, in create_impl
    return WALDisk(logdisk, [datadisk1, datadisk2], osync=False)
  File "waldisk.py", line 22, in waldisk.WALDisk.__init__ (waldisk.c:1819)
    self._logdisk = logdisk
TypeError: Cannot convert AsyncDisk to diskimpl.PartitionAsyncDisk

.....
```

I am using cython 0.25.2:
```
$ python2 -c "from Cython.Compiler.Version import version; print version"
0.25.2
```

**Comment by helgikrs** [comment]
Hi cdetrio,

There are some issues with running the verification on the compiled Cython code. We use Cython only for obtaining a binary for execution, not for verification.

Try `make clean` followed by `make verify` and see if that fixes your problem.
